<?php
/**
 * @package humhub.dev.tonic.ag
 * @author Simon Karlen <simi.albi@gmail.com>
 */

namespace humhub\modules\kanban\widgets;

use humhub\widgets\JsWidget;
use humhub\widgets\Reloadable;
use yii\helpers\ArrayHelper;

/**
 * @property-write array $data
 */
class Task extends JsWidget implements Reloadable
{
    /**
     * @inerhitdoc
     */
    public $jsWidget = 'kanban.Task';

    /**
     * @inerhitdoc
     */
    public $init = true;

    /**
     * Widget data
     * @var array
     */
    private array $_data = [];

    /**
     * {@inheritDoc}
     */
    public function __construct($config = [])
    {
        $this->_data = ArrayHelper::remove($config, 'data', []);
        parent::__construct($config);
    }

    /**
     * {@inheritDoc}
     */
    public function run(): string
    {
        return parent::run(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritDoc}
     */
    protected function getData(): array
    {
        return $this->_data;
    }

    /**
     * {@inheritDoc}
     *
     * @return array
     */
    public function getReloadUrl(): array
    {
        return ['/kanban/task/view', 'id' => $this->getData()['id']];
    }
}
